Add CSV support to calendar
utm-cssc/website pull request #43
Opened 2020-09-22 02:09 UTC by hiimchrislim

2020-09-25 07:00 UTC, hiimchrislim commented
![image](https://user-images.githubusercontent.com/24628243/94236411-2b8a5380-fedb-11ea-9d37-486fab3ef729.png)
Is it possible if we could have the buttons on the bar removed? (i.e. the pencil, heart and triple dot button)

2020-09-26 17:02 UTC, milindvishnoi commented
@hiimchrislim I could not assign you for PR review as you started the PR although I have added @yuhengsu to review it.

2020-09-28 16:12 UTC, ArsalaBangash requested changes
Let's iterate

2020-09-28 16:12 UTC, ArsalaBangash commented on pages/calendar/index.vue
> +        const output = []
What does output denote here?

2020-09-28 16:12 UTC, ArsalaBangash commented on pages/calendar/index.vue
> +                    @click="selectedOpen = false"
Maybe selectedEventFocused is a better var name than selectedOpen?

2020-10-03 18:28 UTC, milindvishnoi commented
@ArsalaBangash Please provide a more comprehensive PR as you mentioned in our last meeting.

2020-10-05 03:53 UTC, ArsalaBangash requested changes
This is a solid elevation. Let's address the comments from my previous and current review, and we'll proceed further. :)

2020-10-05 03:53 UTC, ArsalaBangash commented on content/calendar/CSSC.csv
> +name, description, start_date, start_time, end_date, end_time
I thought we're getting these events from another repo. If these files are duplicated, let's remove them

2020-10-05 03:53 UTC, ArsalaBangash commented on pages/calendar/index.vue
> +                  <v-list-item @click="type = 'day'">
This looks like a fine candidate for a v-for

2020-10-05 03:53 UTC, ArsalaBangash commented on pages/calendar/index.vue
> +              v-model="selectedOpen"
selectedEventFocused here as well

2020-10-05 03:53 UTC, ArsalaBangash commented on pages/calendar/index.vue
> +      if (typeof data === 'string' && data.length > 0) {
Could the data be anything other than string? What are we checking for here?

2020-10-05 09:10 UTC, merged