Completed Dark Mode
utm-cssc/website pull request #74
Opened 2020-11-01 12:09 UTC by milindvishnoi

2020-11-05 17:09 UTC, ArsalaBangash requested changes
Solid iteration!

2020-11-05 17:09 UTC, ArsalaBangash commented on components/global/DarkModeButton.vue
> +import Light from '../../static/svg/sun.svg?inline'
Can we change the path to @/static?

2020-11-05 17:09 UTC, ArsalaBangash commented on components/global/DarkModeButton.vue
> +    Light,
Let's call these LightIcon and DarkIcon

2020-11-05 17:09 UTC, ArsalaBangash commented on components/global/DarkModeButton.vue
> +  width: 35px;
36px since even numbers and multiples of 12 are more commonly used.

2020-11-07 21:32 UTC, hiimchrislim commented
![image](https://user-images.githubusercontent.com/24628243/98451760-d87d0080-2116-11eb-83d0-9b13c96cf4b0.png)
It seems like a few of our fonts and colors aren't applied

2020-11-07 21:36 UTC, hiimchrislim commented
The search bar has 2 colors and the text should perhaps be a dark grey
![image](https://user-images.githubusercontent.com/24628243/98451803-3b6e9780-2117-11eb-9d91-b487177dc1c6.png)

2020-11-07 21:37 UTC, hiimchrislim commented
![image](https://user-images.githubusercontent.com/24628243/98451821-6d7ff980-2117-11eb-8087-754b5cf004c1.png)

If possible, could we use the same color for the sidebar as the one in the (light grey/blue-ish) that says Web Development?

2020-11-07 21:38 UTC, hiimchrislim commented
![image](https://user-images.githubusercontent.com/24628243/98451829-97d1b700-2117-11eb-8574-3668344f3aab.png)
The FAQ will also need to have another color as well (where it's easy to see the accordion cards)

2020-11-07 21:39 UTC, hiimchrislim commented
![image](https://user-images.githubusercontent.com/24628243/98451839-b46def00-2117-11eb-99a9-03ee0dbfdfb9.png)
This is a very minor thing, but is it possible if we could fill in the SVG to a white/grey to it's easier to see the UTMSAM logo?

2020-11-08 18:47 UTC, milindvishnoi commented
@hiimchrislim I have made the required changes, please approve this ASAP coz I'll need this PR for my other gpa-calculator PR.

2020-11-08 19:56 UTC, hiimchrislim commented
Great job!

2020-11-08 19:56 UTC, merged